export default {
  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  SUBMITTING: 'SUBMITTING',
  FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
  RESET_PASSWORD: 'RESET_PASSWORD',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

  TOKEN_REFRESHED: 'TOKEN_REFRESHED',
  TOKEN_REMOVED: 'TOKEN_REMOVED',
  LOGOUT: 'USERS_LOGOUT',

  GET_REQUEST: 'USER_GET_REQUEST',
  GET_SUCCESS: 'USER_GET_SUCCESS',
  GET_FAILURE: 'USER_GET_FAILURE',

  GET_ALL_REQUEST: 'USERS_GET_ALL_REQUEST',
  GET_ALL_SUCCESS: 'USERS_GET_ALL_SUCCESS',
  GET_ALL_FAILURE: 'USERS_GET_ALL_FAILURE',

  UPDATE_REQUEST: 'UPDATE_REQUEST',
  UPDATE_SUCCESS: 'UPDATE_SUCCESS',
  UPDATE_FAILURE: 'UPDATE_FAILURE',

  DELETE_REQUEST: 'USERS_DELETE_REQUEST',
  DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
  DELETE_FAILURE: 'USERS_DELETE_FAILURE'
};
